# Generated by Django 4.1.2 on 2022-11-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bichos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateField()),
                ('animail1', models.CharField(max_length=100)),
                ('animail2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal1_aposta', models.CharField(max_length=100)),
                ('animal2_aposta', models.CharField(max_length=100)),
                ('data_aposta', models.DateField()),
                ('valor_aposta', models.FloatField()),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
        ),
    ]
