# Generated by Django 4.1.2 on 2022-11-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogodobicho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='aposta',
            field=models.ManyToManyField(null=True, to='jogodobicho.aposta'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='animal1_aposta',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='animal2_aposta',
            field=models.CharField(max_length=2),
        ),
    ]
