# Generated by Django 4.1.2 on 2022-10-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
