# Generated by Django 4.1.2 on 2022-10-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0002_rename_numeros_apostas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostas',
            name='clientes',
        ),
    ]
