# Generated by Django 4.1.2 on 2022-10-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0003_remove_apostas_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apostas',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Sorteio',
        ),
    ]
