# Generated by Django 4.1.2 on 2022-10-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0007_remove_apostas_clientes_apostas_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostas',
            name='clientes',
        ),
        migrations.DeleteModel(
            name='Sorteio',
        ),
        migrations.DeleteModel(
            name='Apostas',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
