# Generated by Django 4.1.2 on 2022-10-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loteria', '0008_remove_apostas_clientes_delete_sorteio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=16)),
                ('logar', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor1', models.IntegerField()),
                ('valor2', models.IntegerField()),
                ('valor3', models.IntegerField()),
                ('valor4', models.IntegerField()),
                ('valor5', models.IntegerField()),
                ('valor6', models.IntegerField()),
                ('data_sorteio', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor1', models.IntegerField()),
                ('valor2', models.IntegerField()),
                ('valor3', models.IntegerField()),
                ('valor4', models.IntegerField()),
                ('valor5', models.IntegerField()),
                ('valor6', models.IntegerField()),
                ('data_aposta', models.DateField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.cliente')),
            ],
        ),
    ]
