# Generated by Django 4.1.2 on 2022-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
