# Generated by Django 4.1.2 on 2022-10-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0011_ganhadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganhadores',
            name='cliente',
        ),
        migrations.AddField(
            model_name='ganhadores',
            name='sorteio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loteria.sorteio'),
            preserve_default=False,
        ),
    ]
