# Generated by Django 4.1.2 on 2022-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0013_sorteio_aposta_delete_ganhadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostas',
            name='valor_aposta',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
