# Generated by Django 4.1.2 on 2022-10-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0014_apostas_valor_aposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='logar',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
    ]
