# Generated by Django 4.1.2 on 2022-10-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0016_remove_cliente_cpf_remove_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostas',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loteria.cliente'),
        ),
    ]
