# Generated by Django 4.1.2 on 2022-10-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0018_alter_apostas_clientes_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='aposta',
        ),
        migrations.DeleteModel(
            name='Apostas',
        ),
        migrations.DeleteModel(
            name='Sorteio',
        ),
    ]
