# Generated by Django 4.1.2 on 2022-10-29 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0020_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apostas',
            old_name='clientes',
            new_name='usuario',
        ),
    ]
