# Generated by Django 4.1.2 on 2022-10-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0021_rename_clientes_apostas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteio',
            name='aposta',
        ),
        migrations.DeleteModel(
            name='Apostas',
        ),
        migrations.DeleteModel(
            name='Sorteio',
        ),
    ]
