# Generated by Django 5.1.1 on 2024-10-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0023_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteio',
            name='aposta',
            field=models.ManyToManyField(to='loteria.apostas'),
        ),
    ]
